version: '3.9'

services:
  restrotime-mongo:
    image: mongo:6.0
    container_name: restrotime-mongo
    restart: always
    command: --replSet rs0
    ports:
      - 27017:27017
    volumes:
      - restrotime-mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: restrotime-mongo
      INIT_WAIT_SEC: 3

volumes:
  restrotime-mongo:
